// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/browserforwarder/config.proto

package com.v2ray.core.app.browserforwarder;

/**
 * <pre>
 * Config is the settings for BrowserForwarder.
 * </pre>
 *
 * Protobuf type {@code v2ray.core.app.browserforwarder.Config}
 */
public final class Config extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.app.browserforwarder.Config)
    ConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Config.newBuilder() to construct.
  private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Config() {
    listenAddr_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Config();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Config(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            listenAddr_ = s;
            break;
          }
          case 16: {

            listenPort_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.app.browserforwarder.ConfigOuterClass.internal_static_v2ray_core_app_browserforwarder_Config_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.app.browserforwarder.ConfigOuterClass.internal_static_v2ray_core_app_browserforwarder_Config_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.app.browserforwarder.Config.class, com.v2ray.core.app.browserforwarder.Config.Builder.class);
  }

  public static final int LISTEN_ADDR_FIELD_NUMBER = 1;
  private volatile java.lang.Object listenAddr_;
  /**
   * <code>string listen_addr = 1;</code>
   * @return The listenAddr.
   */
  @java.lang.Override
  public java.lang.String getListenAddr() {
    java.lang.Object ref = listenAddr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      listenAddr_ = s;
      return s;
    }
  }
  /**
   * <code>string listen_addr = 1;</code>
   * @return The bytes for listenAddr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getListenAddrBytes() {
    java.lang.Object ref = listenAddr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      listenAddr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LISTEN_PORT_FIELD_NUMBER = 2;
  private int listenPort_;
  /**
   * <code>int32 listen_port = 2;</code>
   * @return The listenPort.
   */
  @java.lang.Override
  public int getListenPort() {
    return listenPort_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(listenAddr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, listenAddr_);
    }
    if (listenPort_ != 0) {
      output.writeInt32(2, listenPort_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(listenAddr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, listenAddr_);
    }
    if (listenPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, listenPort_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.app.browserforwarder.Config)) {
      return super.equals(obj);
    }
    com.v2ray.core.app.browserforwarder.Config other = (com.v2ray.core.app.browserforwarder.Config) obj;

    if (!getListenAddr()
        .equals(other.getListenAddr())) return false;
    if (getListenPort()
        != other.getListenPort()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LISTEN_ADDR_FIELD_NUMBER;
    hash = (53 * hash) + getListenAddr().hashCode();
    hash = (37 * hash) + LISTEN_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getListenPort();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.app.browserforwarder.Config parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.browserforwarder.Config parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.app.browserforwarder.Config prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Config is the settings for BrowserForwarder.
   * </pre>
   *
   * Protobuf type {@code v2ray.core.app.browserforwarder.Config}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.app.browserforwarder.Config)
      com.v2ray.core.app.browserforwarder.ConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.app.browserforwarder.ConfigOuterClass.internal_static_v2ray_core_app_browserforwarder_Config_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.app.browserforwarder.ConfigOuterClass.internal_static_v2ray_core_app_browserforwarder_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.app.browserforwarder.Config.class, com.v2ray.core.app.browserforwarder.Config.Builder.class);
    }

    // Construct using com.v2ray.core.app.browserforwarder.Config.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      listenAddr_ = "";

      listenPort_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.app.browserforwarder.ConfigOuterClass.internal_static_v2ray_core_app_browserforwarder_Config_descriptor;
    }

    @java.lang.Override
    public com.v2ray.core.app.browserforwarder.Config getDefaultInstanceForType() {
      return com.v2ray.core.app.browserforwarder.Config.getDefaultInstance();
    }

    @java.lang.Override
    public com.v2ray.core.app.browserforwarder.Config build() {
      com.v2ray.core.app.browserforwarder.Config result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.v2ray.core.app.browserforwarder.Config buildPartial() {
      com.v2ray.core.app.browserforwarder.Config result = new com.v2ray.core.app.browserforwarder.Config(this);
      result.listenAddr_ = listenAddr_;
      result.listenPort_ = listenPort_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.app.browserforwarder.Config) {
        return mergeFrom((com.v2ray.core.app.browserforwarder.Config)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.app.browserforwarder.Config other) {
      if (other == com.v2ray.core.app.browserforwarder.Config.getDefaultInstance()) return this;
      if (!other.getListenAddr().isEmpty()) {
        listenAddr_ = other.listenAddr_;
        onChanged();
      }
      if (other.getListenPort() != 0) {
        setListenPort(other.getListenPort());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.v2ray.core.app.browserforwarder.Config parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.v2ray.core.app.browserforwarder.Config) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object listenAddr_ = "";
    /**
     * <code>string listen_addr = 1;</code>
     * @return The listenAddr.
     */
    public java.lang.String getListenAddr() {
      java.lang.Object ref = listenAddr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        listenAddr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string listen_addr = 1;</code>
     * @return The bytes for listenAddr.
     */
    public com.google.protobuf.ByteString
        getListenAddrBytes() {
      java.lang.Object ref = listenAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        listenAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string listen_addr = 1;</code>
     * @param value The listenAddr to set.
     * @return This builder for chaining.
     */
    public Builder setListenAddr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      listenAddr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string listen_addr = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearListenAddr() {
      
      listenAddr_ = getDefaultInstance().getListenAddr();
      onChanged();
      return this;
    }
    /**
     * <code>string listen_addr = 1;</code>
     * @param value The bytes for listenAddr to set.
     * @return This builder for chaining.
     */
    public Builder setListenAddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      listenAddr_ = value;
      onChanged();
      return this;
    }

    private int listenPort_ ;
    /**
     * <code>int32 listen_port = 2;</code>
     * @return The listenPort.
     */
    @java.lang.Override
    public int getListenPort() {
      return listenPort_;
    }
    /**
     * <code>int32 listen_port = 2;</code>
     * @param value The listenPort to set.
     * @return This builder for chaining.
     */
    public Builder setListenPort(int value) {
      
      listenPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 listen_port = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearListenPort() {
      
      listenPort_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.app.browserforwarder.Config)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.app.browserforwarder.Config)
  private static final com.v2ray.core.app.browserforwarder.Config DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.app.browserforwarder.Config();
  }

  public static com.v2ray.core.app.browserforwarder.Config getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Config>
      PARSER = new com.google.protobuf.AbstractParser<Config>() {
    @java.lang.Override
    public Config parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Config(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Config> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Config> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.v2ray.core.app.browserforwarder.Config getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

